// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcproxy.proto

/*
Package grpcproxypb is a generated protocol buffer package.

It is generated from these files:
	grpcproxy.proto

It has these top-level messages:
*/
package grpcproxypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Grpcproxy service

type GrpcproxyClient interface {
}

type grpcproxyClient struct {
	cc *grpc.ClientConn
}

func NewGrpcproxyClient(cc *grpc.ClientConn) GrpcproxyClient {
	return &grpcproxyClient{cc}
}

// Server API for Grpcproxy service

type GrpcproxyServer interface {
}

func RegisterGrpcproxyServer(s *grpc.Server, srv GrpcproxyServer) {
	s.RegisterService(&_Grpcproxy_serviceDesc, srv)
}

var _Grpcproxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproxypb.Grpcproxy",
	HandlerType: (*GrpcproxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "grpcproxy.proto",
}

func init() { proto.RegisterFile("grpcproxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 59 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2f, 0x2a, 0x48,
	0x2e, 0x28, 0xca, 0xaf, 0xa8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86, 0x0b, 0x14,
	0x24, 0x19, 0x71, 0x73, 0x71, 0xba, 0xc3, 0xb8, 0x49, 0x6c, 0x60, 0x05, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc4, 0x06, 0x42, 0x1c, 0x33, 0x00, 0x00, 0x00,
}
